### **Tower of Hanoi Problem**

In [1]:
# hanoi
# https://www.mathsisfun.com/games/towerofhanoi.html

def hanoi(n, start, helper, target):
    if n == 1:
        print(f"n=1 Move disk from {start} to {target}")  # Base case: Move one disk
    else:
        hanoi(n - 1, start, target, helper)  # Step 1: Move (n-1) disks to helper
        print(f"Move disk from {start} to {target}")  # Step 2: Move nth disk to target
        hanoi(n - 1, helper, start, target)  # Step 3: Move (n-1) disks from helper to target

# Run example with 3 disks
hanoi(3, 'Start', 'Helper', 'Target')


# hanoi(3, s, h, t)
#         hanoi(2, s, t, h)
#             hanoi(1, s, h, t)
#                 print(s--> t)
#          print(s --> h)
#             hanoi(1, t, s, h)
#                 print(t--> h)
#          print(s--> t)
#     hanoi(2, h, s, t)
#         hanoi(1, h, t, s)
#                 print(h--> s)
#       print(h --> t)
#         hanoi(1, s, h, t)
#                 print(s --> t)

n=1 Move disk from Start to Target
Move disk from Start to Helper
n=1 Move disk from Target to Helper
Move disk from Start to Target
n=1 Move disk from Helper to Start
Move disk from Helper to Target
n=1 Move disk from Start to Target


### **Quicksort Algorithm**

In [2]:
def quicksort(arr):
    if len(arr) <= 1:  # Base case: A list of 0 or 1 elements is already sorted
        return arr

    pivot = arr[0]  # Choose the first element as the pivot
    left = [x for x in arr[1:] if x <= pivot]  # Elements smaller than or equal to pivot
    right = [x for x in arr[1:] if x > pivot]  # Elements greater than pivot

    return quicksort(left) + [pivot] + quicksort(right)  # Recursively sort left and right

a = [5, 3, 8, 4, 2, 7, 1] # left[3,4,2,1] pivot=5 right[8,7]
# left[2,1] pivot=3 right[4]
# left[1,2,3,4] + pivot[5] + right[7,8]
b = quicksort(a)
print(b)

[1, 2, 3, 4, 5, 7, 8]


## **Homework-07: Chapters 4, 5 and 6 in Python One-Liners**

In [3]:
# Problem 1

## Dependencies
import numpy as np

## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.5, 0.5],
                     [0.1, 0.2, 0.1]])

## One-liner
max_income = np.max(salaries - salaries * taxation)

## Result
print(max_income)

81.0


In [4]:
# Problem 2

a = np.array([6, 4, 2, 9, 5, 1, 8, 3, 7])
      # i =   0, 1, 2, 3, 4, 5, 6, 7, 8
      #-i =   0,-8,-7,-6,-5,-4,-3,-2,-1

print(a) # prints [6 4 2 9 5 1 8 3 7]
print(a[:]) # prints [6 4 2 9 5 1 8 3 7]
print(a[4:]) # prints [5 1 8 3 7]
print(a[:4]) # prints [6 4 2 9]
print(a[3:8]) # prints [9 5 1 8 3]

print(a[5:-2]) # prints [1 8]
print(a[-2:3]) # prints []
print(a[-2:3:-1]) # prints [3 8 1 5]

print(a[::-1]) # prints [7 3 8 1 5 9 2 4 6]
print(a[4::2]) # prints [5 8 7]

print(a[:3:-2]) # prints [7 8 5]
print(a[:2:-2]) # prints [7 8 5]

print(a[-1::-2]) # prints [7 8 5 2 6]
print(a[-1:0:-2]) # prints [7 8 5 2]

[6 4 2 9 5 1 8 3 7]
[6 4 2 9 5 1 8 3 7]
[5 1 8 3 7]
[6 4 2 9]
[9 5 1 8 3]
[1 8]
[]
[3 8 1 5]
[7 3 8 1 5 9 2 4 6]
[5 8 7]
[7 8 5]
[7 8 5]
[7 8 5 2 6]
[7 8 5 2]


In [5]:
# Problem 3

import numpy as np

a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 1, 2],
              [3, 4, 5, 0]])

print(a[:, 1]) # second column
# [1 5 9 4]

print(a[2, :]) # third row
# [8 9 1 2]

print(a[3, ::-1]) # fourth row backwards
# [0 5 4 3]

############# a[row_start:row_end, col_start:col_end] ###############

# m=row, n=column
# a[:-m, :-n] # Exclude last m rows and n columns

print(a[:-2, :-2]) # all lines and columns except last two
# [[0 1]
#  [4 5]]

# a[-m: ,-n: ] take only last m rows and n columns
print(a[-2:, -2:]) # all lines and columns except first two
# [[1 2]
#  [5 0]]

print(a[-1:-2:-1, ]) # last row
# [[3 4 5 0]]

print(a[:-2, -2:]) # top two rows intersected with last two columns
# [[2 3]
#  [6 7]]

print(a[1:3,1:3]) # middle two by two matrix
# [[5 6]
#  [9 1]]

print(a[::-1, ::-1]) # reversed rows in reverse
# [[0 5 4 3]
#  [2 1 9 8]
#  [7 6 5 4]
#  [3 2 1 0]]

[1 5 9 4]
[8 9 1 2]
[0 5 4 3]
[[0 1]
 [4 5]]
[[1 2]
 [5 0]]
[[3 4 5 0]]
[[2 3]
 [6 7]]
[[5 6]
 [9 1]]
[[0 5 4 3]
 [2 1 9 8]
 [7 6 5 4]
 [3 2 1 0]]


Broadcasting simplifies mathematical operations on arrays with different shapes. It enables NumPy to efficiently apply operations element-wise without explicitly copying or reshaping data.

In [6]:
# Problem 4

a = np.array([
              [1, 2, 0],
              [4, 5, 3],
              [6, 8, 7]
            ])

a[::2] += 1 # broadcasting happens here

print (a) # prints [[2 3 1] [[4 5 3] [7 9 8]]
# rows 1 and 3 have their elements incremented by one

print("------------")

a[:, ::2] += 1 # broadcasting, again

print(a) # prints [[3 3 2] [5 5 4] [8 9 9]]
# columns 1 and 3 have their elements incremented by one

print("------------")

a[:,:] -= 1 # what is broadcasting?
print(a) # prints [[2 2 1] [4 4 3] [7 8 8]]
# all elements decremented by one

print("------------")
print(a.shape) # prints (3, 3)
print(a[1].shape) # prints (3,)
print(a.ndim) # prints 2
print(a[0].ndim) # prints 1

[[2 3 1]
 [4 5 3]
 [7 9 8]]
------------
[[3 3 2]
 [5 5 4]
 [8 9 9]]
------------
[[2 2 1]
 [4 4 3]
 [7 8 8]]
------------
(3, 3)
(3,)
2
1


In [7]:
# Problem 5

a = np.array([
              [0, 1, 0],
              [2, 0, 0],
              [3, 0, 3]
            ])

print(np.nonzero(a)) # prints (array([0, 1, 2, 2]), array([1, 0, 0, 2]))
print(np.average(a)) # prints 1.0 (9/9)
print(a > np.average(a)) # prints [[False False False] [ True False False] [ True False  True]]

print("---------------------------------------------")

b = np.array(["One", "Two", "Three"])

print(np.nonzero(a > np.average(a))) # (array([1, 2, 2]), array([0, 0, 2]))
print(np.nonzero(a > np.average(a))[0]) # [1 2 2]

print(b[ np.nonzero(a > np.average(a)) [0] ]) # ['Two' 'Three' 'Three']
print(set(b[ np.nonzero(a > np.average(a)) [0] ])) # {'Two', 'Three'}

(array([0, 1, 2, 2]), array([1, 0, 0, 2]))
1.0
[[False False False]
 [ True False False]
 [ True False  True]]
---------------------------------------------
(array([1, 2, 2]), array([0, 0, 2]))
[1 2 2]
['Two' 'Three' 'Three']
{'Three', 'Two'}


In [8]:
# Problem 6

a = np.array([[25, "mgbako"  ],  # pu away
              [15, "mgbako"  ],  # wi away
              [16, "reneau"  ],  # mi at home
              [19, "reneau"  ],  # msu away
              [16, "goode"   ],  # ucla home
              [15, "galloway"],  # pu home
              [15, "reneau"  ]]) # pu home

## One-liner
b = a[a[:,0].astype(float) > a[:,0].astype(float).min(), 1]

# a[:,0].astype(float) -> selects all the rows but only 0th column and then converts it into float
# a[:,0].astype(float).min() -> gives 15.
# Filtering Rows Where Column 0 Is Greater Than the Minimum -> a[:,0].astype(float) > a[:,0].astype(float).min()
# then it selects only from the column 1 and stores the names

## Results
print(b) # prints ['mgbako' 'reneau' 'reneau' 'goode']
print(set(b)) # prints {'mgbako', 'reneau', 'goode'}

['mgbako' 'reneau' 'reneau' 'goode']
{'reneau', 'goode', 'mgbako'}


In [9]:
# Problem 7

a = np.array([1, 2, 3, 4, 5, 6])

a[1::2] = 1 # a = [1,1,3,1,5,1] # Shape (6,)
print(a.reshape(2, -1)) # prints [[1 1 3] [1 5 1]]

print("------------------------------")

a[2::3] = np.sum(a.reshape((-1,3)), axis=1)
print(a) # prints [1 1 5 1 5 7]
# replace every third value with the sum of the last three values

print("------------------------------")

points = np.array([15, 15, 16, 19, 16, 15, 25])
players = np.array(["reneau", "galloway", "goode", "reneau", "reneau", "mgbako", "mgbako"])

print(np.sort(points)) # prints [15 15 15 16 16 19 25]
print(np.argsort(points)) # prints [0 1 5 2 4 3 6]

# players[np.argsort(points)] → Rearrange players in the same sorted order.
print(players[np.argsort(points)][0:3]) # prints ['reneau' 'galloway' 'mgbako']

# prints names of bottom three top scorers

print("------------------------------")

numbers = np.array([5, 1, 4, 6, 2, 3])
numbers = numbers.reshape(-1, 3)

print(numbers) # prints [[5 1 4] [6 2 3]]
print(max(numbers, key = lambda x : x[1])) # prints [6 2 3] # Finds the row with the highest value in column 1 (index 1).
# from the last problem in chapter 3

[[1 1 3]
 [1 5 1]]
------------------------------
[1 1 5 1 5 7]
------------------------------
[15 15 15 16 16 19 25]
[0 1 5 2 4 3 6]
['reneau' 'galloway' 'mgbako']
------------------------------
[[5 1 4]
 [6 2 3]]
[6 2 3]


**Regex**

In [10]:
# Problem 8

import re

# re.sub(pattern, replacement, input)

input = "I am happy."

print(re.sub('[aeiou]', '-', input)) # prints I -m h-ppy. # Replaces each vowel with '-'.

print(re.sub('[^aeiou]', '-', input)) # prints --a---a---- # Replaces each consonant with '-'.

print(re.sub('([^aeiou\s.])', r'(\1)', input)) # prints (I) a(m) (h)a(p)(p)(y).
# [^aeiou\s.] → Matches any character that is NOT a vowel, space, or period.
# () around \1 in replacement → Wraps the matched character inside parentheses.


print(re.sub('(\W)(\w)', r'\2\1', input)) # prints Ia mh appy.
# \W → Matches any non-word character (spaces, punctuation)
# \w → Matches any word character (letters, digits)
# r'\2\1' → Swaps positions of the matched groups.


print(re.sub('(\w)(\W)', r'\2\1', input)) # prints  Ia mhapp.y

print(re.sub('([aeiou])([^aeiou\s])', r'\2\1', input)) # prints I ma hpapy.
# ([aeiou]) → Matches a vowel (a, e, i, o, u).
# ([^aeiou\s]) → Matches any consonant, but not spaces.

I -m h-ppy.
--a---a----
(I) a(m) (h)a(p)(p)(y).
Ia mh appy.
 Ia mhapp.y
I ma hpapy.


In [11]:
# Problem 9

input = "Once 9123 upon a 4567 there was a 12389"
print(input) # prints Once 9123 upon a 4567 there was a 12389

result = re.sub('\d\d', '-', input)
print(result) # prints Once -- upon a -- there was a --9


# Pattern: \d((\d)(\d))\d
# \d → Matches a digit before and after the captured group.
# ((\d)(\d)) → Captures two digits inside a bigger group.
# \1 → First captured group (second and third digit).
# \3 → Third captured group (third digit).

result = re.sub('\d((\d)(\d))\d', r'\1+\3', input)
# This pattern replaces a string with a part of itself
print(result) # prints Once 12+2 upon a 56+6 there was a 23+39

julianne = "2364523"
result = re.sub('(\d)(\d)', r'\1+\2', julianne)
print(result) # prints 2+36+45+23

def add_two(match):
    return str(int(match.group()) + 2)

s = 'Alex 28'
result = re.sub(r'(\d+)', add_two, s)
print(result) # prints Alex 30

# \d+ → Matches any sequence of digits (28)

suraj = re.sub(r'(\d)(\d)', lambda m: str(int(m.group(1)) + int(m.group(2))), s)
print(suraj) # prints Alex 10

# Pattern: (\d)(\d)
# Matches two consecutive digits.
# Replacement: Adds them together.

linjun = "12345"
suraj = re.sub(r'(\d)(\d)', lambda m: m.group(2) + m.group(1), linjun)
                #                     \2           \1
print(suraj) # prints 21435

# same as above just reverse the order

text = "I am here."
text = re.sub('(\w)', r'(\1)', text)
print(text) # prints (I) (a)(m) (h)(e)(r)(e).

Once 9123 upon a 4567 there was a 12389
Once -- upon a -- there was a --9
Once 12+2 upon a 56+6 there was a 23+39
2+36+45+23
Alex 30
Alex 10
21435
(I) (a)(m) (h)(e)(r)(e).


In [12]:
# Problem 10

def nuf(a, b):
    return int(a) + int(b)

def fun(match): # , eggplant):
    a = nuf(match.group(1), match.group(2))
    print(match) # what gets printed with this?
    return str(a) # match.group(2) + match.group(1)

word = "12345"
result = re.sub('(\d)(\d)', fun, word)
# (\d)(\d) → Captures two consecutive digits.
# 1,2 got matched and 3,4 got matched which returned 3,7 from the function
print(result) # prints 375

mark = map(lambda num : num + 1, [8, 1, 2, 3, 2, 5]) # just adds one to each element
print(list(mark)) # prints [9, 2, 3, 4, 3, 6]

word = "The works."
result1 = re.sub('(\w)', r'(\1)', word)
result2 = re.sub('(\w)', '(\1)', word)
#'(\1)' (without r'') is treated as a normal string, not a raw string.

print(result1) # prints (T)(h)(e) (w)(o)(r)(k)(s).
print(result2) # prints ()()() ()()()()().

<re.Match object; span=(0, 2), match='12'>
<re.Match object; span=(2, 4), match='34'>
375
[9, 2, 3, 4, 3, 6]
(T)(h)(e) (w)(o)(r)(k)(s).
()()() ()()()()().


**Regression**

In [13]:
# Problem 11

from sklearn.linear_model import LinearRegression
import numpy as np

## Data (Apple stock prices)
apple = np.array([157, 156, 159, 159])
n = len(apple)

## One-liner
model = LinearRegression().fit(np.arange(n).reshape((n,1)), apple)
# np.arrange(n) = [0,1,2,3]
# np.arange(n).reshape((n,1))
# Becomes:
# [[0]
#  [1]
#  [2]
#  [3]]

# X = [[0], [1], [2], [3]] (time steps)
# y = [157, 156, 159, 159] (stock prices)

# y = mx+c formula

## Result & puzzle
print(model.predict([[4],[5],[6]]))

[160.  160.9 161.8]


In [14]:
# Problem 12

from sklearn.linear_model import LogisticRegression

## Data (#cigarettes, cancer)
X = np.array([[0, "No"],
              [10, "No"],
              [60, "Yes"],
              [90, "Yes"]])

## One-liner
model = LogisticRegression().fit(X[:,0].reshape(n,1), X[:,1])

# X[:,0] do? Selects only the first column (number of cigarettes).
# .reshape(n,1)?
# X[:,0] gives a 1D array, but sklearn expects a 2D array (n,1).
# reshape(n,1) ensures it is correctly formatted.

# then x and y fits into logistic regression which works on sigmoid function

## Result & puzzle
print(model.predict([[12],[29],[34],[36],[38],[41],[58]]))

['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes']


Supervised Learning: